# Generated by Django 4.0.1 on 2022-04-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsPearl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_model', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('date_certified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatternsDies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_part', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=100)),
                ('set', models.CharField(max_length=100)),
            ],
        ),
    ]
